# Generated by Django 5.1.3 on 2024-11-11 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='name',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='surname',
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='phone_number',
            field=models.CharField(max_length=13),
        ),
    ]
