# Generated by Django 5.1.3 on 2024-11-11 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_usermodel_name_remove_usermodel_surname_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserModel',
        ),
    ]
